#!/bin/bash
# coding:utf-8

#================================================================================
# 以下を出力する
# ・経過時間 (ミリ秒)
# ・プロセスCPU使用率
#   + 親プロセス
#   + 親子合計
#   + 子プロセス毎
# ・プロセスメモリ使用量
#   + 親プロセス
#   + 親子合計
#   + 子プロセス毎
# ・free
# ・iostat
# ・vmstat
#================================================================================

USAGE="USAGE: $0 [PID] [INTERVAL] [OUTDIR]"

PID=$1
INTERVAL=${2:-1}
PROF_DIR=${3:-profile}

mkdir -p $PROF_DIR
IOSTAT_FILE=$PROF_DIR/iostat.txt
VMSTAT_FILE=$PROF_DIR/vmstat.txt
NDSTAT_FILE=$PROF_DIR/ndstat.txt
FREE_FILE=$PROF_DIR/free.txt
PS_FILE=$PROF_DIR/ps.txt

ndstat() {
    interval=$1
    while :
    do
        echo `date +'%Y/%m/%d %H:%M:%S'`
        cat /proc/net/dev
        echo
        sleep $interval
    done
}

mon_free() {
    interval=$1
    while :
    do
        echo `date +'%Y/%m/%d %H:%M:%S'`
        free
        echo
        sleep $interval
    done
}

mon_ps() {
    pid=$1
    interval=$2
    while :
    do
        echo `date +'%Y/%m/%d %H:%M:%S'`
        ps uh -p $pid
        ps uh --ppid=$pid
        echo
        sleep $interval
    done
}

# iostat
echo -n >$IOSTAT_FILE
iostat -tyx $INTERVAL >>$IOSTAT_FILE &
IOSTAT_PID=$!
echo "iostat: $IOSTAT_PID"

# vmstat
echo -n >$VMSTAT_FILE
vmstat -nt $INTERVAL >>$VMSTAT_FILE &
VMSTAT_PID=$!
echo "vmstat: $VMSTAT_PID"

# ndstat
echo -n >$NDSTAT_FILE
ndstat $INTERVAL >>$NDSTAT_FILE &
NDSTAT_PID=$!
echo "ndstat: $NDSTAT_PID"

# free
echo -n >$FREE_FILE
mon_free $INTERVAL >>$FREE_FILE &
FREE_PID=$!
echo "free: $FREE_PID"

# ps info
echo -n >$PS_FILE
mon_ps $PID $INTERVAL >>$PS_FILE &
PS_PID=$!
echo "ps: $PS_PID"

FINISH_FLAG=0

kill_if_alive() {
    pid=$1
    if [ `ps -p $pid >/dev/null 2>&1; echo $?` -eq 0 ]; then
        kill $pid
    fi
}

finalize() {
    echo "finalize" >&2
    kill_if_alive $IOSTAT_PID
    kill_if_alive $VMSTAT_PID
    kill_if_alive $NDSTAT_PID
    kill_if_alive $FREE_PID
    kill_if_alive $PS_PID
    FINISH_FLAG=1
}

trap finalize USR1 TERM INT

while :
do
    if [ $FINISH_FLAG -eq 1 ]; then
        break
    fi

    sleep $INTERVAL
done
