#!/bin/bash
# coding:utf-8

#================================================================================
# 各種リソースの使用状況を指定したインターバルごとに記録する
# ・iostat -> iostat.txt
# ・vmstat -> vmstat.txt
# ・/proc/net/dev -> ndstat.txt
# ・free -> free.txt
# ・ps -> ps.txt
#================================================================================

USAGE="USAGE: $0 [PID] [INTERVAL] [OUTDIR]"

PID=$1
INTERVAL=${2:-1}
PROF_DIR=${3:-measure_result}

mkdir -p $PROF_DIR
IOSTAT_FILE=$PROF_DIR/iostat.txt
VMSTAT_FILE=$PROF_DIR/vmstat.txt
NDSTAT_FILE=$PROF_DIR/ndstat.txt
FREE_FILE=$PROF_DIR/free.txt
PS_FILE=$PROF_DIR/ps.txt

finalize() {
    finish_flag=1
}

ndstat() {
    interval=$1
    finish_flag=0

    trap finalize TERM

    while [ $finish_flag -eq 0 ]
    do
        echo `date +'%Y/%m/%d %H:%M:%S'`
        cat /proc/net/dev
        echo
        sleep $interval
    done
}

mon_free() {
    interval=$1
    finish_flag=0

    trap finalize TERM

    while [ $finish_flag -eq 0 ]
    do
        echo `date +'%Y/%m/%d %H:%M:%S'`
        free
        echo
        sleep $interval
    done
}

mon_ps() {
    pid=$1
    interval=$2
    finish_flag=0

    trap finalize TERM

    while [ $finish_flag -eq 0 ]
    do
        echo `date +'%Y/%m/%d %H:%M:%S'`
        ps uh -p $pid
        ps uh --ppid=$pid
        echo
        sleep $interval
    done
}

# iostat
echo -n >$IOSTAT_FILE
iostat -tyx $INTERVAL >>$IOSTAT_FILE &
IOSTAT_PID=$!
echo "iostat: $IOSTAT_PID"

# vmstat
echo -n >$VMSTAT_FILE
vmstat -nt $INTERVAL >>$VMSTAT_FILE &
VMSTAT_PID=$!
echo "vmstat: $VMSTAT_PID"

# ndstat
echo -n >$NDSTAT_FILE
ndstat $INTERVAL >>$NDSTAT_FILE &
NDSTAT_PID=$!
echo "ndstat: $NDSTAT_PID"

# free
echo -n >$FREE_FILE
mon_free $INTERVAL >>$FREE_FILE &
FREE_PID=$!
echo "free: $FREE_PID"

# ps info
echo -n >$PS_FILE
mon_ps $PID $INTERVAL >>$PS_FILE &
PS_PID=$!
echo "ps: $PS_PID"

FINISH_FLAG=0

kill_if_alive() {
    pid=$1
    if [ `ps -p $pid >/dev/null 2>&1; echo $?` -eq 0 ]; then
        kill $pid
    fi
}

kill_procs() {
    echo "finalize" >&2
    kill_if_alive $IOSTAT_PID
    kill_if_alive $VMSTAT_PID
    kill_if_alive $NDSTAT_PID
    kill_if_alive $FREE_PID
    kill_if_alive $PS_PID
    FINISH_FLAG=1
}

trap kill_procs USR1 TERM INT

while :
do
    if [ $FINISH_FLAG -eq 1 ]; then
        break
    fi

    sleep $INTERVAL
done
